Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -20,34 +20,44 @@ jobs:
       timeout-minutes: 15
       run: ./mvnw -B verify
 
-    - name: Get JaCoCo Coverage
-      id: coverage  
-      run: |
-        coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv) 
-        echo "COVERAGE=$coverage" >> $GITHUB_ENV
+    # - name: Get JaCoCo Coverage
+    #   id: coverage  
+    #   run: |
+    #     coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv) 
+    #     echo "COVERAGE=$coverage" >> $GITHUB_ENV
 
-    - name: Fail if coverage has not improved.
-      run: |
-        coverage=$COVERAGE
-        threshold=24.46
-        if (( $(echo "$coverage - $threshold <= 0.1" | bc -l) )); then
-          echo "Coverage is not improved."
-          exit 1
-        else
-          echo "New coverage: $coverage%. Coverage is improved!"
-        fi
+    # - name: Fail if coverage has not improved.
+    #   run: |
+    #     coverage=$COVERAGE
+    #     threshold=24.46
+    #     if (( $(echo "$coverage - $threshold <= 0.1" | bc -l) )); then
+    #       echo "Coverage is not improved."
+    #       exit 1
+    #     else
+    #       echo "New coverage: $coverage%. Coverage is improved!"
+    #     fi
         
-    - name: Run build with MaxRAM flag
+    # - name: Run build with MaxRAM flag
+    #   run: |
+    #     export MAVEN_OPTS="-XX:MaxRAM=2g"  # Set MaxRAM flag
+    #     mvn clean install  # Run Maven build
+        
+    # # Check if the compilation was successful with 2GB RAM
+    # - name: Check if build was successful with 2GB RAM
+    #   if: success()  
+    #   run: echo "The build with 2GB RAM was successful."
+
+    # # Check error
+    # - name: Handle failure
+    #   if: failure()  
+    #   run: echo "Build with 2GB RAM failed."
+
+    - name: flag
       run: |
-        export MAVEN_OPTS="-XX:MaxRAM=2g"  # Set MaxRAM flag
+        export MAVEN_OPTS="-Xlog:gc*:file=gc.log"  # Set MaxRAM flag
         mvn clean install  # Run Maven build
-        
-    # Check if the compilation was successful with 2GB RAM
-    - name: Check if build was successful with 2GB RAM
-      if: success()  
-      run: echo "The build with 2GB RAM was successful."
 
-    # Check error
-    - name: Handle failure
-      if: failure()  
-      run: echo "Build with 2GB RAM failed."
+    - name: Ejecutar script de Bash para obtener GC Info
+      run: |
+        chmod +x ./search_gc_info.sh
+        ./search_gc_info.sh
